### ISSUE TITLE
if use-cert-manager, handler deployment will fail

### ISSUE THREAD

**Issue by owenchenxy** [h3poteto/fluentd-sidecar-injector#226]
When I specified --use-cert-manager in manager.yaml like below, the handler pod will fail because required secrets will not be created.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-sidecar-injector-manager
  namespace: kube-system
  labels:
    operator.h3poteto.dev: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      operator.h3poteto.dev: control-plane
  template:
    metadata:
      labels:
        operator.h3poteto.dev: control-plane
    spec:
      serviceAccountName: fluentd-sidecar-injector-manager
      containers:
        - name: manager
          image: "registry:5000/x86_64/fluentd-sidecar-injector:0.7.1"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 200Mi
          args:
            - /fluentd-sidecar-injector
            - controller
            - sidecar-injector
            - --use-cert-manager
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WEBHOOK_CONTAINER_IMAGE
              value: "registry:5000/x86_64/fluentd-sidecar-injector:0.7.1"
```

failed pod information is as below:
```
# kubectl -n kube-system describe deployments.apps fluentd-sidecar-injector-fluentd-handler
Name:                   fluentd-sidecar-injector-fluentd-handler
Namespace:              kube-system
CreationTimestamp:      Thu, 03 Mar 2022 17:22:23 +0800
Labels:                 sidecarinjectors.operator.h3poteto.dev=webhook-deployment
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               sidecarinjectors.operator.h3poteto.dev=webhook-pod
Replicas:               2 desired | 2 updated | 2 total | 0 available | 2 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           sidecarinjectors.operator.h3poteto.dev=webhook-pod
  Service Account:  default
  Containers:
   webhook-handler:
    Image:      registry:5000/x86_64/fluentd-sidecar-injector:0.7.1
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      /fluentd-sidecar-injector
      webhook
      --tls-cert-file=/etc/webhook/certs/tls.crt
      --tls-key-file=/etc/webhook/certs/tls.key
    Limits:
      cpu:     0
      memory:  0
    Requests:
      cpu:      0
      memory:   0
    Liveness:   tcp-socket :8080 delay=30s timeout=60s period=20s #success=1 #failure=4
    Readiness:  tcp-socket :8080 delay=30s timeout=60s period=10s #success=2 #failure=2
    Environment:
      COLLECTOR:             fluentd
      FLUENTD_DOCKER_IMAGE:  registry:5000/x86_64/fluentd-forward:latest
    Mounts:
      /etc/webhook/certs from webhook-certs (ro)
  Volumes:
   webhook-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sidecar-injector-certs-fluentd-sidecar-injector-fluentd
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  <none>
NewReplicaSet:   fluentd-sidecar-injector-fluentd-handler-67ff444f98 (2/2 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  6m18s  deployment-controller  Scaled up replica set fluentd-sidecar-injector-fluentd-handler-67ff444f98 to 2
root@qingcloud-firstbox:/pitrix/conf/k8s/testkube/operator# kubectl -n kube-system describe pod fluentd-sidecar-injector-fluentd-handler-67ff444f98-p64lq
Name:           fluentd-sidecar-injector-fluentd-handler-67ff444f98-p64lq
Namespace:      kube-system
Priority:       0
Node:           testkubear02n01/172.16.80.9
Start Time:     Thu, 03 Mar 2022 17:22:23 +0800
Labels:         pod-template-hash=67ff444f98
                sidecarinjectors.operator.h3poteto.dev=webhook-pod
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/fluentd-sidecar-injector-fluentd-handler-67ff444f98
Containers:
  webhook-handler:
    Container ID:
    Image:         registry:5000/x86_64/fluentd-sidecar-injector:0.7.1
    Image ID:
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      /fluentd-sidecar-injector
      webhook
      --tls-cert-file=/etc/webhook/certs/tls.crt
      --tls-key-file=/etc/webhook/certs/tls.key
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     0
      memory:  0
    Requests:
      cpu:      0
      memory:   0
    Liveness:   tcp-socket :8080 delay=30s timeout=60s period=20s #success=1 #failure=4
    Readiness:  tcp-socket :8080 delay=30s timeout=60s period=10s #success=2 #failure=2
    Environment:
      COLLECTOR:             fluentd
      FLUENTD_DOCKER_IMAGE:  registry:5000/x86_64/fluentd-forward:latest
    Mounts:
      /etc/webhook/certs from webhook-certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pkjlk (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  webhook-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sidecar-injector-certs-fluentd-sidecar-injector-fluentd
    Optional:    false
  default-token-pkjlk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pkjlk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    37m                  default-scheduler  Successfully assigned kube-system/fluentd-sidecar-injector-fluentd-handler-67ff444f98-p64lq to testkubear02n01
  Warning  FailedMount  15m (x8 over 31m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[webhook-certs], unattached volumes=[webhook-certs default-token-pkjlk]: timed out waiting for the condition
  Warning  FailedMount  7m3s (x23 over 37m)  kubelet            MountVolume.SetUp failed for volume "webhook-certs" : secret "sidecar-injector-certs-fluentd-sidecar-injector-fluentd" not found
  Warning  FailedMount  101s (x3 over 35m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[webhook-certs], unattached volumes=[default-token-pkjlk webhook-certs]: timed out waiting for the condition
```

I inspected the code, found that if "--use-cert-manager" was specified, the secrets used by volumes of deployment would not be created. [Code link](https://github.com/h3poteto/fluentd-sidecar-injector/blob/master/pkg/controller/sidecarinjector/controller.go#L280) 
However, the deployment templates didn't check the condition to determine whether to use the secret(it just uses the secrets anyhow).[Code link](https://github.com/h3poteto/fluentd-sidecar-injector/blob/master/pkg/controller/sidecarinjector/generator.go#L160)

Could you confirm if this is a known bug or by design?
